# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aad6eafc3f2196a9c0783de1cc5299a6885859684fe0d8fd4b2d3d15475f9b096f2ec9028bca1c96cba83326c5764f2fa88aa3f3ce1824b6aa4611627b6bd06a

test:
  secret_key_base: ce48fb983742e51fcc0fcb35f065942d3b3cc18bdfc27c0d56bf5d29add9d2901e5270d3e275260f87b3dfb050c9279e35018d8c7ae63ee200c68d289a5c8bf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
